### ISSUE TITLE
Problem installing package using pip

### ISSUE THREAD

**Issue by vertangelx** [emesik/monero-python#19]
Ran `pip install monero-python` on an Ubuntu bash, received the following error. Help appreciated, thank you

    Collecting monero-python
      Using cached https://files.pythonhosted.org/packages/ef/57/7fa1459cff9ddf603ffa43aeff88399290b7602bad34981224599d67c240/monero-python-0.2.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-install-j96wybcp/monero-python/setup.py", line 5, in <module>
            version = __import__('monero').__version__
          File "/tmp/pip-install-j96wybcp/monero-python/monero/__init__.py", line 1, in <module>
            from . import address, account, daemon, wallet, numbers, prio, wordlists, seed
          File "/tmp/pip-install-j96wybcp/monero-python/monero/address.py", line 4, in <module>
            from sha3 import keccak_256
        ModuleNotFoundError: No module named 'sha3'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-j96wybcp/monero-python/

**Comment by lalanza808** [comment]
Try installing `pysha3` first:

`pip install pysha3 && pip install monero-python`

**Comment by emesik** [comment]
Actually, `pip` should install dependencies automatically. Doesn't it?

**Comment by rooterkyberian** [comment]
yes, the problem is that `setup.py` which is supposed to do that, first tries to figure out the version number which it does by importing `monero` package, which in turn right of the bat tries to import `sha3`, hence the error
