### ISSUE TITLE
13 word mnemonic seed

### ISSUE THREAD

**Issue by vertangelx** [emesik/monero-python#21]
Why does the library supports 25 word mnemonic seeds but not **13 word** mnemonic seeds such as that created by MyMonero?

Any chance for the support of 13 word mnemonic seeds to be implemented?

**Comment by emesik** [comment]
Currently it's not available, because I assumed that command is rarely used in automated environment. However, the implementation should be straightforward, so I'll try to include it in the next release.

**Comment by emesik** [comment]
How does the 13 word seed work? Are there any docs on that?

**Comment by emesik** [comment]
OK, I see where it's failing. There's a test in commit c9b4a5c7cb4c879c00fac1de20400dc7e8adbbb0

@lalanza808 can you check that?

**Comment by emesik** [comment]
Fixed in 83eca24ce01444883367565ad7a4fda75c6d8f76
