### ISSUE TITLE
Monero v0.13.0.2 support and version update to pypi

### ISSUE THREAD

**Issue by john-doe-a112** [emesik/monero-python#34]
Hello,

Thanks for the great module.

Monero v0.13.0.2 with bulletproofs support will be active in the network on Oct. 18.

Does monero-python support this version?

Also, I observed that monero-python 0.4.3 was released, but it's not on pypi. Can you update the program version in pypi?

Thanks.

**Comment by emesik** [comment]
Thanks for your words of appreciation. Yes, we are ready for the hard fork. The main change in `monero-python` 0.4.3 is enforced ring size of 11. Version 0.4.2 will also work after the fork, provided that the external code calls `transfer()` and `transfer_multiple()` with `ringsize=11`.

I'm finishing tests and 0.4.3 will be released to pypi ASAP.

**Comment by emesik** [comment]
0.4.3 has been released and is available on PyPi
